# Generated by Django 6.1.1 on 2026-10-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
