# Generated by Django 6.1 on 2026-10-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_paciente_cpf_alter_paciente_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
